# Generated by Django 5.0 on 2024-01-19 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("volobotapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="section",
            old_name="s_name",
            new_name="student_name",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="s_name",
            new_name="student_name",
        ),
    ]
