# Generated by Django 5.0 on 2024-01-19 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("volobotapp", "0002_rename_s_name_section_student_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="section",
            name="student_name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
