# Generated by Django 5.0 on 2024-01-19 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("volobotapp", "0004_alter_section_student_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="section",
            old_name="student_name",
            new_name="name",
        ),
    ]
